# WebSocket tunnel configuration
tunnelId = "1cf2755f-c151-4281-b3f0-55c399035f87"

# WebSocket server URL to connect to
# wsUrl = "ws://localhost:4443"
wsUrl = "wss://tunnel.remotelinker.io"
#wsUrl = "wss://flows-hybrid.yousolution.it"

# Target URL where the traffic will be forwarded
targetUrl = "http://localhost:1880"

# Optional URL for tunnel entry point (if applicable)
tunnelEntryUrl = "http://localhost:3032"

# TCP port to open for incoming tunnel connections
tunnelEntryPort = 3032

# Whether to allow insecure SSL certificates (dev/test only)
allowInsicureCerts = true

# Log verbosity level: error, warn, info, debug, trace
logLevel = "trace"

# Environment
environment = "production"

[headers]
Authorization = "Bearer YOUR_JWT_TOKEN_HERE"
x-websocket-tunnel-port = "3030"